### ISSUE TITLE
Airflow: Armada Deferrable Operator undefined object attribute 'poll_interval'

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#2972]
Version `0.5.5` of the Armada Deferrable Operator for Airflow raises an exception due to an undefined object attribute `poll_interval`:
```
[2023-09-13, 09:05:01 UTC] {taskinstance.py:1598} ERROR - Trigger failed:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/triggerer_job_runner.py", line 537, in cleanup_finished_triggers
    result = details["task"].result()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/jobs/triggerer_job_runner.py", line 615, in run_trigger
    async for event in trigger.run():
  File "/home/airflow/.local/lib/python3.10/site-packages/armada/operators/armada_deferrable.py", line 263, in run
    poll_interval=self.poll_interval,
AttributeError: 'ArmadaJobCompleteTrigger' object has no attribute 'poll_interval'
[2023-09-13, 09:05:01 UTC] {taskinstance.py:1824} ERROR - Task failed with exception
airflow.exceptions.TaskDeferralError: Trigger failure
```

**Comment by richscott** [comment]
Closing - this is fixed in commit 291ef41a on Sep 18, 2023.
